/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Factory": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "FactoryApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "FactoryRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "Pos": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "PosApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "PosRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
  }
}

import "sst"
export {}